export enum GarmentCategory {
  ACCESSORIES = 'Accessories',
  BAGS = 'Bags',
  OUTERWEAR = 'Outerwear',
  DRESSES = 'Dresses',
  TOPS = 'Tops',
  BOTTOMS = 'Bottoms',
  SHOES = 'Shoes',
  OTHER = 'Other',
}

export const DEFAULT_CATEGORY_PATHS = [
  'Tops & t-shirts > T-shirts',
  'Tops & t-shirts > Blouses',
  'Tops & t-shirts > Crop tops',
  'Tops & t-shirts > Vest tops & tank tops',
  'Tops & t-shirts > Shirts',
  'Tops & t-shirts > Short-sleeved tops',
  'Tops & t-shirts > Long-sleeved tops',
  'Tops & t-shirts > Off-the-shoulder tops',
  'Tops & t-shirts > Bodysuits',
  'Tops & t-shirts > Halterneck tops',
  'Tops & t-shirts > Other tops & t-shirts',
  'Tops & t-shirts > 3/4-sleeve tops',
  'Tops & t-shirts > Tunics',
  'Tops & t-shirts > Camis',
  'Tops & t-shirts > Peplum tops',
  'Tops & t-shirts > Turtlenecks',
  'Dresses > Summer dresses',
  'Dresses > Long dresses',
  'Dresses > Special-occasion dresses',
  'Dresses > Mini-dresses',
  'Dresses > Midi-dresses',
  'Dresses > Little black dresses',
  'Dresses > Casual dresses',
  'Dresses > Formal & work dresses',
  'Dresses > Winter dresses',
  'Dresses > Other dresses',
  'Dresses > Denim dresses',
  'Dresses > Strapless dresses',
  'Jumpers & sweaters > Jumpers',
  'Jumpers & sweaters > Hoodies & sweatshirts',
  'Jumpers & sweaters > Cardigans',
  'Jumpers & sweaters > Waistcoats',
  'Jumpers & sweaters > Other jumpers & sweaters',
  'Jumpers & sweaters > Kimonos',
  'Jumpers & sweaters > Boleros',
  'Trousers & leggings > Wide-leg trousers',
  'Trousers & leggings > Straight-leg trousers',
  'Trousers & leggings > Leggings',
  'Trousers & leggings > Other trousers',
  'Trousers & leggings > Cropped trousers & chinos',
  'Trousers & leggings > Skinny trousers',
  'Trousers & leggings > Tailored trousers',
  'Trousers & leggings > Leather trousers',
  'Trousers & leggings > Harem pants',
  'Skirts > Mini skirts',
  'Skirts > Maxi skirts',
  'Skirts > Knee-length skirts',
  'Skirts > Midi skirts',
  'Skirts > Asymmetric skirts',
  'Skorts',
  'Jeans > Straight jeans',
  'Jeans > Skinny jeans',
  'Jeans > High waisted jeans',
  'Jeans > Flared jeans',
  'Jeans > Ripped jeans',
  'Jeans > Other',
  'Jeans > Boyfriend jeans',
  'Jeans > Cropped jeans',
  'Shorts & cropped trousers > Denim shorts',
  'Shorts & cropped trousers > High-waisted shorts',
  'Shorts & cropped trousers > Other shorts & cropped trousers',
  'Shorts & cropped trousers > Cropped trousers',
  'Shorts & cropped trousers > Low-waisted shorts',
  'Shorts & cropped trousers > Knee-length shorts',
  'Shorts & cropped trousers > Cargo shorts',
  'Shorts & cropped trousers > Lace shorts',
  'Shorts & cropped trousers > Leather shorts',
  'Outerwear > Jackets',
  'Outerwear > Coats',
  'Outerwear > Gilets & body warmers',
  'Outerwear > Capes & ponchos',
  'Activewear > Tops & t-shirts',
  'Activewear > Shorts',
  'Activewear > Trousers',
  'Activewear > Tracksuits',
  'Activewear > Sports bras',
  'Activewear > Dresses',
  'Activewear > Sports accessories',
  'Activewear > Outerwear',
  'Activewear > Skirts',
  'Activewear > Other activewear',
  'Activewear > Hoodies & sweatshirts',
  'Activewear > Team shirts & jerseys',
  'Swimwear > Bikinis & tankinis',
  'Swimwear > One-pieces',
  'Swimwear > Cover-ups & sarongs',
  'Swimwear > Other swimwear & beachwear',
  'Suits & blazers > Blazers',
  'Suits & blazers > Trouser suits',
  'Suits & blazers > Skirt suits',
  'Suits & blazers > Suit separates',
  'Suits & blazers > Other suits & blazers',
  'Lingerie & nightwear > Bras',
  'Lingerie & nightwear > Nightwear',
  'Lingerie & nightwear > Sets',
  'Lingerie & nightwear > Panties',
  'Lingerie & nightwear > Lingerie accessories',
  'Lingerie & nightwear > Socks',
  'Lingerie & nightwear > Tights & stockings',
  'Lingerie & nightwear > Dressing gowns',
  'Lingerie & nightwear > Shapewear',
  'Lingerie & nightwear > Other',
  'Jumpsuits & playsuits > Jumpsuits',
  'Jumpsuits & playsuits > Playsuits',
  'Jumpsuits & playsuits > Onesies',
  'Costumes & special outfits',
  'Other clothing',
  'Accessories > Glasses',
  'Accessories > Gloves',
  'Accessories > Belts',
  'Accessories > Hats',
  'Accessories > Jewellery',
  'Accessories > Scarves',
  'Accessories > Sunglasses',
  'Accessories > Ties',
  'Accessories > Watches',
  'Bags > Backpacks',
  'Bags > Bum bags',
  'Bags > Crossbody bags',
  'Bags > Duffle bags',
  'Bags > Handbags',
  'Bags > Laptop bags',
  'Bags > Shoulder bags',
  'Bags > Totes',
  'Shoes > Sneakers',
  'Shoes > Boots > Ankle boots',
  'Shoes > Boots > Knee-high boots',
  'Shoes > Boots > Mid-calf boots',
  'Shoes > Boots > Snow boots',
  'Shoes > Boots > Over-the-knee boots',
  'Shoes > Boots > Work boots',
  'Shoes > Boots > Wellington boots',
  'Shoes > Heels',
  'Shoes > Sandals',
  'Shoes > Flip-flops & slides',
  'Shoes > Sports shoes',
  'Shoes > Espadrilles',
  'Shoes > Ballerinas',
  'Shoes > Boat shoes, loafers & moccasins',
  'Shoes > Clogs & mules',
  'Shoes > Lace-up shoes',
  'Shoes > Mary Janes & T-bar shoes',
  'Shoes > Slippers',
  'Other',
];

export const TOP_LEVEL_CATEGORIES = [
  'All',
  'Clothing',
  'Shoes',
  'Tops & t-shirts',
  'Dresses',
  'Jumpers & sweaters',
  'Trousers & leggings',
  'Skirts',
  'Jeans',
  'Shorts & cropped trousers',
  'Outerwear',
  'Activewear',
  'Swimwear',
  'Suits & blazers',
  'Accessories',
  'Bags',
];

export const SIZE_GROUPS = [
  {
    label: 'Clothing sizes',
    sizes: [
      'XXS',
      'XS',
      'S',
      'M',
      'L',
      'XL',
      'XXL',
      'XXXL',
      '4XL',
      '5XL',
      '6XL',
    ],
  },
  {
    label: 'Shoe sizes',
    sizes: [
      '35 EU',
      '36 EU',
      '37 EU',
      '38 EU',
      '39 EU',
      '40 EU',
      '41 EU',
      '42 EU',
      '43 EU',
      '44 EU',
      '45 EU',
      '46 EU',
      '47 EU',
    ],
  },
];
