export enum GarmentCategory {
  ACCESSORIES = 'Accessories',
  BAGS = 'Bags',
  OUTERWEAR = 'Outerwear',
  DRESSES = 'Dresses',
  TOPS = 'Tops',
  BOTTOMS = 'Bottoms',
  SHOES = 'Shoes',
  OTHER = 'Other',
}

export const DEFAULT_CATEGORY_PATHS = [
  'Accessories > Belts',
  'Accessories > Hats',
  'Accessories > Jewellery',
  'Accessories > Scarves',
  'Bags > Backpacks',
  'Bags > Handbags',
  'Bags > Totes',
  'Bottoms > Jeans > Ripped jeans',
  'Bottoms > Jeans > Skinny jeans',
  'Bottoms > Jeans > Slim fit jeans',
  'Bottoms > Jeans > Straight fit jeans',
  'Bottoms > Shorts',
  'Bottoms > Skirts',
  'Bottoms > Skorts',
  'Bottoms > Trousers',
  'Dresses',
  'Hoodies & Sweaters > Hoodies',
  'Hoodies & Sweaters > Knitwear',
  'Hoodies & Sweaters > Sweatshirts',
  'Outerwear > Blazers',
  'Outerwear > Coats',
  'Outerwear > Jackets',
  'Outerwear > Puffers',
  'Shoes > Sneakers',
  'Shoes > Boots > Ankle boots',
  'Shoes > Boots > Chelsea boots',
  'Shoes > Boots > Over-knee boots',
  'Shoes > Boots > Combat boots',
  'Shoes > Loafers',
  'Shoes > Heels',
  'Shoes > Sandals',
  'Shoes > Low tops',
  'Shoes > High tops',
  'Tops > Blouses',
  'Tops > Crop tops',
  'Tops > Shirts',
  'Tops > T-shirts',
  'Tops > Tank tops',
  'Other',
];

export const TOP_LEVEL_CATEGORIES = [
  'All',
  'Clothing',
  'Shoes',
  'Outerwear',
  'Tops & T-shirts',
  'Trousers',
  'Jeans',
  'Hoodies & Sweaters',
];

export const SIZE_GROUPS = [
  {
    label: "Men's sizes",
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', '4XL', '5XL', '6XL'],
  },
  {
    label: "Women's sizes",
    sizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL'],
  },
  {
    label: 'Shoe sizes',
    sizes: [
      '35 EU',
      '36 EU',
      '37 EU',
      '38 EU',
      '39 EU',
      '40 EU',
      '41 EU',
      '42 EU',
      '43 EU',
      '44 EU',
      '45 EU',
      '46 EU',
      '47 EU',
    ],
  },
];
