export enum GarmentCategory {
  ACCESSORIES = 'Accessories',
  BAGS = 'Bags',
  OUTERWEAR = 'Outerwear',
  DRESSES = 'Dresses',
  TOPS = 'Tops',
  BOTTOMS = 'Bottoms',
  SHOES = 'Shoes',
  OTHER = 'Other',
}

export const DEFAULT_CATEGORY_PATHS = [
  'Accessories > Glasses',
  'Accessories > Gloves',
  'Accessories > Belts',
  'Accessories > Hats',
  'Accessories > Jewellery',
  'Accessories > Scarves',
  'Accessories > Sunglasses',
  'Accessories > Ties',
  'Accessories > Watches',
  'Bags > Backpacks',
  'Bags > Bum bags',
  'Bags > Crossbody bags',
  'Bags > Duffle bags',
  'Bags > Handbags',
  'Bags > Laptop bags',
  'Bags > Shoulder bags',
  'Bags > Totes',
  'Bottoms > Cargo pants',
  'Bottoms > Chinos',
  'Bottoms > Jeans > Ripped jeans',
  'Bottoms > Jeans > Skinny jeans',
  'Bottoms > Jeans > Slim fit jeans',
  'Bottoms > Jeans > Straight fit jeans',
  'Bottoms > Jeans > Wide leg jeans',
  'Bottoms > Joggers',
  'Bottoms > Leggings',
  'Bottoms > Shorts > Cargo shorts',
  'Bottoms > Shorts > Denim shorts',
  'Bottoms > Shorts > Sports shorts',
  'Bottoms > Skirts > Maxi skirts',
  'Bottoms > Skirts > Midi skirts',
  'Bottoms > Skirts > Mini skirts',
  'Bottoms > Skorts',
  'Bottoms > Trousers > Cargo trousers',
  'Bottoms > Trousers > Cropped trousers',
  'Bottoms > Trousers > Formal trousers',
  'Bottoms > Trousers > Wide leg trousers',
  'Dresses > Casual dresses',
  'Dresses > Evening dresses',
  'Dresses > Maxi dresses',
  'Dresses > Midi dresses',
  'Dresses > Mini dresses',
  'Dresses > Shirt dresses',
  'Dresses > Summer dresses',
  'Hoodies & Sweaters > Cardigans',
  'Hoodies & Sweaters > Hoodies > Pullover hoodies',
  'Hoodies & Sweaters > Hoodies > Zip hoodies',
  'Hoodies & Sweaters > Knitwear > Jumpers',
  'Hoodies & Sweaters > Knitwear > Sweater vests',
  'Hoodies & Sweaters > Sweatshirts > Crewnecks',
  'Hoodies & Sweaters > Sweatshirts > Oversized sweatshirts',
  'Outerwear > Blazers > Casual blazers',
  'Outerwear > Blazers > Formal blazers',
  'Outerwear > Coats > Parkas',
  'Outerwear > Coats > Trench coats',
  'Outerwear > Coats > Wool coats',
  'Outerwear > Jackets > Bomber jackets',
  'Outerwear > Jackets > Denim jackets',
  'Outerwear > Jackets > Leather jackets',
  'Outerwear > Jackets > Windbreakers',
  'Outerwear > Puffers > Puffer jackets',
  'Outerwear > Puffers > Puffer vests',
  'Shoes > Sneakers',
  'Shoes > Boots > Ankle boots',
  'Shoes > Boots > Chelsea boots',
  'Shoes > Boots > Over-knee boots',
  'Shoes > Boots > Combat boots',
  'Shoes > Boots > Hiking boots',
  'Shoes > Boots > Knee-high boots',
  'Shoes > Flats > Ballet flats',
  'Shoes > Flats > Loafers',
  'Shoes > Flats > Moccasins',
  'Shoes > Heels',
  'Shoes > Sandals',
  'Shoes > Slippers',
  'Shoes > Sports shoes',
  'Suits & Sets > Co-ords',
  'Suits & Sets > Suits',
  'Suits & Sets > Tracksuits',
  'Tops > Blouses',
  'Tops > Crop tops',
  'Tops > Long sleeve tops',
  'Tops > Polo shirts',
  'Tops > Shirts > Casual shirts',
  'Tops > Shirts > Formal shirts',
  'Tops > Sports tops',
  'Tops > T-shirts',
  'Tops > Tank tops',
  'Tops > Vests',
  'Other',
];

export const TOP_LEVEL_CATEGORIES = [
  'All',
  'Clothing',
  'Shoes',
  'Outerwear',
  'Tops & T-shirts',
  'Trousers',
  'Jeans',
  'Hoodies & Sweaters',
  'Accessories',
  'Bags',
];

export const SIZE_GROUPS = [
  {
    label: "Men's sizes",
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', '4XL', '5XL', '6XL'],
  },
  {
    label: "Women's sizes",
    sizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL'],
  },
  {
    label: 'Shoe sizes',
    sizes: [
      '35 EU',
      '36 EU',
      '37 EU',
      '38 EU',
      '39 EU',
      '40 EU',
      '41 EU',
      '42 EU',
      '43 EU',
      '44 EU',
      '45 EU',
      '46 EU',
      '47 EU',
    ],
  },
];
